import type { BackgroundOption } from './products'

// AUTO-GENERATED FILE. Do not edit by hand.
// Run: npm run generate:backgrounds

export const DISCOVERED_FLUX_BACKGROUNDS: BackgroundOption[] = [
  { id: 'flux-11-image', name: '11', path: '/backgrounds/11.png', thumbnail: '/backgrounds/thumbnails/11.jpg' },
  { id: 'flux-12-image', name: '12', path: '/backgrounds/12.png', thumbnail: '/backgrounds/thumbnails/12.jpg' },
  { id: 'flux-13-image', name: '13', path: '/backgrounds/13.png', thumbnail: '/backgrounds/thumbnails/13.jpg' },
  { id: 'flux-14-image', name: '14', path: '/backgrounds/14.png', thumbnail: '/backgrounds/thumbnails/14.jpg' },
  { id: 'flux-15-image', name: '15', path: '/backgrounds/15.png', thumbnail: '/backgrounds/thumbnails/15.jpg' },
  { id: 'flux-16-image', name: '16', path: '/backgrounds/16.png', thumbnail: '/backgrounds/thumbnails/16.jpg' },
  { id: 'flux-17-image', name: '17', path: '/backgrounds/17.png', thumbnail: '/backgrounds/thumbnails/17.jpg' },
  { id: 'flux-18-image', name: '18', path: '/backgrounds/18.png', thumbnail: '/backgrounds/thumbnails/18.jpg' },
  { id: 'flux-19-image', name: '19', path: '/backgrounds/19.png', thumbnail: '/backgrounds/thumbnails/19.jpg' },
  { id: 'flux-20-image', name: '20', path: '/backgrounds/20.png', thumbnail: '/backgrounds/thumbnails/20.jpg' },
  { id: 'flux-21-image', name: '21', path: '/backgrounds/21.png', thumbnail: '/backgrounds/thumbnails/21.jpg' },
  { id: 'flux-22-image', name: '22', path: '/backgrounds/22.png', thumbnail: '/backgrounds/thumbnails/22.jpg' },
  { id: 'flux-23-image', name: '23', path: '/backgrounds/23.png', thumbnail: '/backgrounds/thumbnails/23.jpg' },
  { id: 'flux-24-image', name: '24', path: '/backgrounds/24.png', thumbnail: '/backgrounds/thumbnails/24.jpg' },
  { id: 'flux-25-image', name: '25', path: '/backgrounds/25.png', thumbnail: '/backgrounds/thumbnails/25.jpg' },
  { id: 'flux-26-image', name: '26', path: '/backgrounds/26.png', thumbnail: '/backgrounds/thumbnails/26.jpg' },
  { id: 'flux-27-image', name: '27', path: '/backgrounds/27.png', thumbnail: '/backgrounds/thumbnails/27.jpg' },
  { id: 'flux-28-image', name: '28', path: '/backgrounds/28.png', thumbnail: '/backgrounds/thumbnails/28.jpg' },
  { id: 'flux-29-image', name: '29', path: '/backgrounds/29.png', thumbnail: '/backgrounds/thumbnails/29.jpg' },
  { id: 'flux-30-image', name: '30', path: '/backgrounds/30.png', thumbnail: '/backgrounds/thumbnails/30.jpg' },
  { id: 'flux-31-image', name: '31', path: '/backgrounds/31.png', thumbnail: '/backgrounds/thumbnails/31.jpg' },
  { id: 'flux-32-image', name: '32', path: '/backgrounds/32.png', thumbnail: '/backgrounds/thumbnails/32.jpg' },
  { id: 'flux-33-image', name: '33', path: '/backgrounds/33.png', thumbnail: '/backgrounds/thumbnails/33.jpg' },
  { id: 'flux-34-image', name: '34', path: '/backgrounds/34.png', thumbnail: '/backgrounds/thumbnails/34.jpg' },
  { id: 'flux-35-image', name: '35', path: '/backgrounds/35.png', thumbnail: '/backgrounds/thumbnails/35.jpg' },
  { id: 'flux-36-image', name: '36', path: '/backgrounds/36.png', thumbnail: '/backgrounds/thumbnails/36.jpg' },
  { id: 'flux-37-image', name: '37', path: '/backgrounds/37.png', thumbnail: '/backgrounds/thumbnails/37.jpg' },
  { id: 'flux-38-image', name: '38', path: '/backgrounds/38.png', thumbnail: '/backgrounds/thumbnails/38.jpg' },
  { id: 'flux-39-image', name: '39', path: '/backgrounds/39.png', thumbnail: '/backgrounds/thumbnails/39.jpg' },
  { id: 'flux-40-image', name: '40', path: '/backgrounds/40.png', thumbnail: '/backgrounds/thumbnails/40.jpg' },
  { id: 'flux-41-image', name: '41', path: '/backgrounds/41.png', thumbnail: '/backgrounds/thumbnails/41.jpg' },
  { id: 'flux-42-image', name: '42', path: '/backgrounds/42.png', thumbnail: '/backgrounds/thumbnails/42.jpg' },
  { id: 'flux-43-image', name: '43', path: '/backgrounds/43.png', thumbnail: '/backgrounds/thumbnails/43.jpg' },
  { id: 'flux-44-image', name: '44', path: '/backgrounds/44.png', thumbnail: '/backgrounds/thumbnails/44.jpg' },
  { id: 'flux-45-image', name: '45', path: '/backgrounds/45.png', thumbnail: '/backgrounds/thumbnails/45.jpg' },
  { id: 'flux-eight-image', name: 'Eight', path: '/backgrounds/eight.png', thumbnail: '/backgrounds/thumbnails/eight.jpg' },
  { id: 'flux-five-image', name: 'Five', path: '/backgrounds/five.png', thumbnail: '/backgrounds/thumbnails/five.jpg' },
  { id: 'flux-fluxcloud openclaw-image', name: 'Fluxcloud Openclaw', path: '/backgrounds/fluxcloud openclaw.png', thumbnail: '/backgrounds/fluxcloud openclaw.png' },
  { id: 'flux-fluxcloud openclaw loop-video', name: 'Fluxcloud Openclaw Loop (Video)', path: '/backgrounds/fluxcloud openclaw loop.mp4', thumbnail: '/backgrounds/fluxcloud openclaw.png', type: 'video' },
  { id: 'flux-four-image', name: 'Four', path: '/backgrounds/four.png', thumbnail: '/backgrounds/thumbnails/four.jpg' },
  { id: 'flux-nine-image', name: 'Nine', path: '/backgrounds/nine.png', thumbnail: '/backgrounds/thumbnails/nine.jpg' },
  { id: 'flux-one-image', name: 'One', path: '/backgrounds/one.png', thumbnail: '/backgrounds/thumbnails/one.jpg' },
  { id: 'flux-seven-image', name: 'Seven', path: '/backgrounds/seven.png', thumbnail: '/backgrounds/thumbnails/seven.jpg' },
  { id: 'flux-six-image', name: 'Six', path: '/backgrounds/six.png', thumbnail: '/backgrounds/thumbnails/six.jpg' },
  { id: 'flux-ten-image', name: 'Ten', path: '/backgrounds/ten.png', thumbnail: '/backgrounds/thumbnails/ten.jpg' },
  { id: 'flux-three-image', name: 'Three', path: '/backgrounds/three.png', thumbnail: '/backgrounds/thumbnails/three.jpg' },
  { id: 'flux-two-image', name: 'Two', path: '/backgrounds/two.png', thumbnail: '/backgrounds/thumbnails/two.jpg' }
]

export const DISCOVERED_SSP_BACKGROUNDS: BackgroundOption[] = [
  { id: 'ssp-1 hour setup-image', name: '1 Hour Setup', path: '/products/ssp/backgrounds/1 hour setup.png', thumbnail: '/products/ssp/backgrounds/thumbnails/1 hour setup.jpg' },
  { id: 'ssp-1 hour setup-video', name: '1 Hour Setup (Video)', path: '/products/ssp/backgrounds/1 hour setup.mp4', thumbnail: '/products/ssp/backgrounds/thumbnails/1 hour setup.jpg', type: 'video' },
  { id: 'ssp-90 percent cheaper than alternatives-image', name: '90 Percent Cheaper Than Alternatives', path: '/products/ssp/backgrounds/90 percent cheaper than alternatives.png', thumbnail: '/products/ssp/backgrounds/thumbnails/90 percent cheaper than alternatives.jpg' },
  { id: 'ssp-90 percent cheaper than alternatives-video', name: '90 Percent Cheaper Than Alternatives (Video)', path: '/products/ssp/backgrounds/90 percent cheaper than alternatives.mp4', thumbnail: '/products/ssp/backgrounds/thumbnails/90 percent cheaper than alternatives.jpg', type: 'video' },
  { id: 'ssp-biometric security-video', name: 'Biometric Security (Video)', path: '/products/ssp/backgrounds/biometric security.mp4', thumbnail: '/products/ssp/backgrounds/biometric security.mp4', type: 'video' },
  { id: 'ssp-biometrics security-image', name: 'Biometrics Security', path: '/products/ssp/backgrounds/biometrics security.png', thumbnail: '/products/ssp/backgrounds/thumbnails/biometrics security.jpg' },
  { id: 'ssp-complete audit trail-image', name: 'Complete Audit Trail', path: '/products/ssp/backgrounds/complete audit trail.png', thumbnail: '/products/ssp/backgrounds/thumbnails/complete audit trail.jpg' },
  { id: 'ssp-complete audit trail-video', name: 'Complete Audit Trail (Video)', path: '/products/ssp/backgrounds/complete audit trail.mp4', thumbnail: '/products/ssp/backgrounds/thumbnails/complete audit trail.jpg', type: 'video' },
  { id: 'ssp-fully open source-image', name: 'Fully Open Source', path: '/products/ssp/backgrounds/fully open source.png', thumbnail: '/products/ssp/backgrounds/thumbnails/fully open source.jpg' },
  { id: 'ssp-fully open source-video', name: 'Fully Open Source (Video)', path: '/products/ssp/backgrounds/fully open source.mp4', thumbnail: '/products/ssp/backgrounds/thumbnails/fully open source.jpg', type: 'video' },
  { id: 'ssp-generic - main-image', name: 'Generic Main', path: '/products/ssp/backgrounds/generic - main.png', thumbnail: '/products/ssp/backgrounds/thumbnails/generic - main.jpg' },
  { id: 'ssp-generic - main-video', name: 'Generic Main (Video)', path: '/products/ssp/backgrounds/generic - main.mp4', thumbnail: '/products/ssp/backgrounds/thumbnails/generic - main.jpg', type: 'video' },
  { id: 'ssp-multi chain native-image', name: 'Multi Chain Native', path: '/products/ssp/backgrounds/multi chain native.png', thumbnail: '/products/ssp/backgrounds/thumbnails/multi chain native.jpg' },
  { id: 'ssp-multi chain native-video', name: 'Multi Chain Native (Video)', path: '/products/ssp/backgrounds/multi chain native.mp4', thumbnail: '/products/ssp/backgrounds/thumbnails/multi chain native.jpg', type: 'video' },
  { id: 'ssp-multi party approval-image', name: 'Multi Party Approval', path: '/products/ssp/backgrounds/multi party approval.png', thumbnail: '/products/ssp/backgrounds/thumbnails/multi party approval.jpg' },
  { id: 'ssp-mutli part approval-video', name: 'Mutli Part Approval (Video)', path: '/products/ssp/backgrounds/mutli part approval.mp4', thumbnail: '/products/ssp/backgrounds/mutli part approval.mp4', type: 'video' },
  { id: 'ssp-no vendor lock in-image', name: 'No Vendor Lock In', path: '/products/ssp/backgrounds/no vendor lock in.png', thumbnail: '/products/ssp/backgrounds/thumbnails/no vendor lock in.jpg' },
  { id: 'ssp-no vendor lock in-video', name: 'No Vendor Lock In (Video)', path: '/products/ssp/backgrounds/no vendor lock in.mp4', thumbnail: '/products/ssp/backgrounds/thumbnails/no vendor lock in.jpg', type: 'video' },
  { id: 'ssp-sec audit halbron-video', name: 'Sec Audit Halbron (Video)', path: '/products/ssp/backgrounds/sec audit halbron.mp4', thumbnail: '/products/ssp/backgrounds/sec audit halbron.mp4', type: 'video' },
  { id: 'ssp-security audited halborn-image', name: 'Security Audited Halborn', path: '/products/ssp/backgrounds/security audited halborn.png', thumbnail: '/products/ssp/backgrounds/thumbnails/security audited halborn.jpg' },
  { id: 'ssp-true self custody-image', name: 'True Self Custody', path: '/products/ssp/backgrounds/true self custody.png', thumbnail: '/products/ssp/backgrounds/thumbnails/true self custody.jpg' },
  { id: 'ssp-true self custody-video', name: 'True Self Custody (Video)', path: '/products/ssp/backgrounds/true self custody.mp4', thumbnail: '/products/ssp/backgrounds/thumbnails/true self custody.jpg', type: 'video' }
]

export const DISCOVERED_ZELCORE_BACKGROUNDS: BackgroundOption[] = [
  { id: 'zelcore-100k-assets-in-one-wallet-image', name: '100k Assets In One Wallet', path: '/products/zelcore/backgrounds/100k-assets-in-one-wallet.jpg', thumbnail: '/products/zelcore/backgrounds/thumbnails/100k-assets-in-one-wallet.jpg' },
  { id: 'zelcore-100k-assets-in-one-wallet-video', name: '100k Assets In One Wallet (Video)', path: '/products/zelcore/backgrounds/100k-assets-in-one-wallet.mp4', thumbnail: '/products/zelcore/backgrounds/thumbnails/100k-assets-in-one-wallet.jpg', type: 'video' },
  { id: 'zelcore-80-plus-blockchains-supported-image', name: '80 Plus Blockchains Supported', path: '/products/zelcore/backgrounds/80-plus-blockchains-supported.jpg', thumbnail: '/products/zelcore/backgrounds/thumbnails/80-plus-blockchains-supported.jpg' },
  { id: 'zelcore-80-plus-blockchains-supported-video', name: '80 Plus Blockchains Supported (Video)', path: '/products/zelcore/backgrounds/80-plus-blockchains-supported.mp4', thumbnail: '/products/zelcore/backgrounds/thumbnails/80-plus-blockchains-supported.jpg', type: 'video' },
  { id: 'zelcore-biometric-security-image', name: 'Biometric Security', path: '/products/zelcore/backgrounds/biometric-security.jpg', thumbnail: '/products/zelcore/backgrounds/thumbnails/biometric-security.jpg' },
  { id: 'zelcore-biometric-security-video', name: 'Biometric Security (Video)', path: '/products/zelcore/backgrounds/biometric-security.mp4', thumbnail: '/products/zelcore/backgrounds/thumbnails/biometric-security.jpg', type: 'video' },
  { id: 'zelcore-built-for-real-users-image', name: 'Built For Real Users', path: '/products/zelcore/backgrounds/built-for-real-users.jpg', thumbnail: '/products/zelcore/backgrounds/thumbnails/built-for-real-users.jpg' },
  { id: 'zelcore-built-for-real-users-video', name: 'Built For Real Users (Video)', path: '/products/zelcore/backgrounds/built-for-real-users.mp4', thumbnail: '/products/zelcore/backgrounds/thumbnails/built-for-real-users.jpg', type: 'video' },
  { id: 'zelcore-built-in-swap-access-image', name: 'Built In Swap Access', path: '/products/zelcore/backgrounds/built-in-swap-access.jpg', thumbnail: '/products/zelcore/backgrounds/thumbnails/built-in-swap-access.jpg' },
  { id: 'zelcore-built-in-swap-access-video', name: 'Built In Swap Access (Video)', path: '/products/zelcore/backgrounds/built-in-swap-access.mp4', thumbnail: '/products/zelcore/backgrounds/thumbnails/built-in-swap-access.jpg', type: 'video' },
  { id: 'zelcore-buy-sell-send-receive-image', name: 'Buy Sell Send Receive', path: '/products/zelcore/backgrounds/buy-sell-send-receive.jpg', thumbnail: '/products/zelcore/backgrounds/thumbnails/buy-sell-send-receive.jpg' },
  { id: 'zelcore-buy-sell-send-receive-video', name: 'Buy Sell Send Receive (Video)', path: '/products/zelcore/backgrounds/buy-sell-send-receive.mp4', thumbnail: '/products/zelcore/backgrounds/thumbnails/buy-sell-send-receive.jpg', type: 'video' },
  { id: 'zelcore-desktop-mobile-and-browser-image', name: 'Desktop Mobile And Browser', path: '/products/zelcore/backgrounds/desktop-mobile-and-browser.jpg', thumbnail: '/products/zelcore/backgrounds/thumbnails/desktop-mobile-and-browser.jpg' },
  { id: 'zelcore-desktop-mobile-and-browser-video', name: 'Desktop Mobile And Browser (Video)', path: '/products/zelcore/backgrounds/desktop-mobile-and-browser.mp4', thumbnail: '/products/zelcore/backgrounds/thumbnails/desktop-mobile-and-browser.jpg', type: 'video' },
  { id: 'zelcore-free-forever-core-wallet-image', name: 'Free Forever Core Wallet', path: '/products/zelcore/backgrounds/free-forever-core-wallet.jpg', thumbnail: '/products/zelcore/backgrounds/thumbnails/free-forever-core-wallet.jpg' },
  { id: 'zelcore-free-forever-core-wallet-video', name: 'Free Forever Core Wallet (Video)', path: '/products/zelcore/backgrounds/free-forever-core-wallet.mp4', thumbnail: '/products/zelcore/backgrounds/thumbnails/free-forever-core-wallet.jpg', type: 'video' },
  { id: 'zelcore-hardware-wallet-support-image', name: 'Hardware Wallet Support', path: '/products/zelcore/backgrounds/hardware-wallet-support.jpg', thumbnail: '/products/zelcore/backgrounds/thumbnails/hardware-wallet-support.jpg' },
  { id: 'zelcore-hardware-wallet-support-video', name: 'Hardware Wallet Support (Video)', path: '/products/zelcore/backgrounds/hardware-wallet-support.mp4', thumbnail: '/products/zelcore/backgrounds/thumbnails/hardware-wallet-support.jpg', type: 'video' },
  { id: 'zelcore-non-custodial-by-design-image', name: 'Non Custodial By Design', path: '/products/zelcore/backgrounds/non-custodial-by-design.jpg', thumbnail: '/products/zelcore/backgrounds/thumbnails/non-custodial-by-design.jpg' },
  { id: 'zelcore-non-custodial-by-design-video', name: 'Non Custodial By Design (Video)', path: '/products/zelcore/backgrounds/non-custodial-by-design.mp4', thumbnail: '/products/zelcore/backgrounds/thumbnails/non-custodial-by-design.jpg', type: 'video' },
  { id: 'zelcore-one-wallet-full-ownership-image', name: 'One Wallet Full Ownership', path: '/products/zelcore/backgrounds/one-wallet-full-ownership.jpg', thumbnail: '/products/zelcore/backgrounds/thumbnails/one-wallet-full-ownership.jpg' },
  { id: 'zelcore-one-wallet-full-ownership-video', name: 'One Wallet Full Ownership (Video)', path: '/products/zelcore/backgrounds/one-wallet-full-ownership.mp4', thumbnail: '/products/zelcore/backgrounds/thumbnails/one-wallet-full-ownership.jpg', type: 'video' },
  { id: 'zelcore-optional-decentralized-2fa-image', name: 'Optional Decentralized 2fa', path: '/products/zelcore/backgrounds/optional-decentralized-2fa.jpg', thumbnail: '/products/zelcore/backgrounds/thumbnails/optional-decentralized-2fa.jpg' },
  { id: 'zelcore-optional-decentralized-2fa-video', name: 'Optional Decentralized 2fa (Video)', path: '/products/zelcore/backgrounds/optional-decentralized-2fa.mp4', thumbnail: '/products/zelcore/backgrounds/thumbnails/optional-decentralized-2fa.jpg', type: 'video' },
  { id: 'zelcore-portfolio-visibility-image', name: 'Portfolio Visibility', path: '/products/zelcore/backgrounds/portfolio-visibility.jpg', thumbnail: '/products/zelcore/backgrounds/thumbnails/portfolio-visibility.jpg' },
  { id: 'zelcore-portfolio-visibility-video', name: 'Portfolio Visibility (Video)', path: '/products/zelcore/backgrounds/portfolio-visibility.mp4', thumbnail: '/products/zelcore/backgrounds/thumbnails/portfolio-visibility.jpg', type: 'video' },
  { id: 'zelcore-true-self-custody-image', name: 'True Self Custody', path: '/products/zelcore/backgrounds/true-self-custody.jpg', thumbnail: '/products/zelcore/backgrounds/thumbnails/true-self-custody.jpg' },
  { id: 'zelcore-true-self-custody-video', name: 'True Self Custody (Video)', path: '/products/zelcore/backgrounds/true-self-custody.mp4', thumbnail: '/products/zelcore/backgrounds/thumbnails/true-self-custody.jpg', type: 'video' },
  { id: 'zelcore-web3-ready-image', name: 'Web3 Ready', path: '/products/zelcore/backgrounds/web3-ready.jpg', thumbnail: '/products/zelcore/backgrounds/thumbnails/web3-ready.jpg' },
  { id: 'zelcore-web3-ready-video', name: 'Web3 Ready (Video)', path: '/products/zelcore/backgrounds/web3-ready.mp4', thumbnail: '/products/zelcore/backgrounds/thumbnails/web3-ready.jpg', type: 'video' }
]

export const DISCOVERED_FLUXAI_BACKGROUNDS: BackgroundOption[] = [

]
