import type { BackgroundOption } from './products'

// AUTO-GENERATED FILE. Do not edit by hand.
// Run: npm run generate:backgrounds

export const DISCOVERED_FLUX_BACKGROUNDS: BackgroundOption[] = [
  { id: 'flux-11-image', name: '11', path: '/backgrounds/11.png', thumbnail: '/backgrounds/thumbnails/11.jpg' },
  { id: 'flux-12-image', name: '12', path: '/backgrounds/12.png', thumbnail: '/backgrounds/thumbnails/12.jpg' },
  { id: 'flux-13-image', name: '13', path: '/backgrounds/13.png', thumbnail: '/backgrounds/thumbnails/13.jpg' },
  { id: 'flux-14-image', name: '14', path: '/backgrounds/14.png', thumbnail: '/backgrounds/thumbnails/14.jpg' },
  { id: 'flux-15-image', name: '15', path: '/backgrounds/15.png', thumbnail: '/backgrounds/thumbnails/15.jpg' },
  { id: 'flux-16-image', name: '16', path: '/backgrounds/16.png', thumbnail: '/backgrounds/thumbnails/16.jpg' },
  { id: 'flux-17-image', name: '17', path: '/backgrounds/17.png', thumbnail: '/backgrounds/thumbnails/17.jpg' },
  { id: 'flux-18-image', name: '18', path: '/backgrounds/18.png', thumbnail: '/backgrounds/thumbnails/18.jpg' },
  { id: 'flux-19-image', name: '19', path: '/backgrounds/19.png', thumbnail: '/backgrounds/thumbnails/19.jpg' },
  { id: 'flux-20-image', name: '20', path: '/backgrounds/20.png', thumbnail: '/backgrounds/thumbnails/20.jpg' },
  { id: 'flux-21-image', name: '21', path: '/backgrounds/21.png', thumbnail: '/backgrounds/thumbnails/21.jpg' },
  { id: 'flux-22-image', name: '22', path: '/backgrounds/22.png', thumbnail: '/backgrounds/thumbnails/22.jpg' },
  { id: 'flux-23-image', name: '23', path: '/backgrounds/23.png', thumbnail: '/backgrounds/thumbnails/23.jpg' },
  { id: 'flux-24-image', name: '24', path: '/backgrounds/24.png', thumbnail: '/backgrounds/thumbnails/24.jpg' },
  { id: 'flux-25-image', name: '25', path: '/backgrounds/25.png', thumbnail: '/backgrounds/thumbnails/25.jpg' },
  { id: 'flux-26-image', name: '26', path: '/backgrounds/26.png', thumbnail: '/backgrounds/thumbnails/26.jpg' },
  { id: 'flux-27-image', name: '27', path: '/backgrounds/27.png', thumbnail: '/backgrounds/thumbnails/27.jpg' },
  { id: 'flux-28-image', name: '28', path: '/backgrounds/28.png', thumbnail: '/backgrounds/thumbnails/28.jpg' },
  { id: 'flux-29-image', name: '29', path: '/backgrounds/29.png', thumbnail: '/backgrounds/thumbnails/29.jpg' },
  { id: 'flux-30-image', name: '30', path: '/backgrounds/30.png', thumbnail: '/backgrounds/thumbnails/30.jpg' },
  { id: 'flux-31-image', name: '31', path: '/backgrounds/31.png', thumbnail: '/backgrounds/thumbnails/31.jpg' },
  { id: 'flux-32-image', name: '32', path: '/backgrounds/32.png', thumbnail: '/backgrounds/thumbnails/32.jpg' },
  { id: 'flux-33-image', name: '33', path: '/backgrounds/33.png', thumbnail: '/backgrounds/thumbnails/33.jpg' },
  { id: 'flux-34-image', name: '34', path: '/backgrounds/34.png', thumbnail: '/backgrounds/thumbnails/34.jpg' },
  { id: 'flux-35-image', name: '35', path: '/backgrounds/35.png', thumbnail: '/backgrounds/thumbnails/35.jpg' },
  { id: 'flux-36-image', name: '36', path: '/backgrounds/36.png', thumbnail: '/backgrounds/thumbnails/36.jpg' },
  { id: 'flux-37-image', name: '37', path: '/backgrounds/37.png', thumbnail: '/backgrounds/thumbnails/37.jpg' },
  { id: 'flux-38-image', name: '38', path: '/backgrounds/38.png', thumbnail: '/backgrounds/thumbnails/38.jpg' },
  { id: 'flux-39-image', name: '39', path: '/backgrounds/39.png', thumbnail: '/backgrounds/thumbnails/39.jpg' },
  { id: 'flux-40-image', name: '40', path: '/backgrounds/40.png', thumbnail: '/backgrounds/thumbnails/40.jpg' },
  { id: 'flux-41-image', name: '41', path: '/backgrounds/41.png', thumbnail: '/backgrounds/thumbnails/41.jpg' },
  { id: 'flux-42-image', name: '42', path: '/backgrounds/42.png', thumbnail: '/backgrounds/thumbnails/42.jpg' },
  { id: 'flux-43-image', name: '43', path: '/backgrounds/43.png', thumbnail: '/backgrounds/thumbnails/43.jpg' },
  { id: 'flux-44-image', name: '44', path: '/backgrounds/44.png', thumbnail: '/backgrounds/thumbnails/44.jpg' },
  { id: 'flux-45-image', name: '45', path: '/backgrounds/45.png', thumbnail: '/backgrounds/thumbnails/45.jpg' },
  { id: 'flux-eight-image', name: 'Eight', path: '/backgrounds/eight.png', thumbnail: '/backgrounds/thumbnails/eight.jpg' },
  { id: 'flux-five-image', name: 'Five', path: '/backgrounds/five.png', thumbnail: '/backgrounds/thumbnails/five.jpg' },
  { id: 'flux-fluxcloud openclaw-image', name: 'Fluxcloud Openclaw', path: '/backgrounds/fluxcloud openclaw.png', thumbnail: '/backgrounds/fluxcloud openclaw.png' },
  { id: 'flux-fluxcloud openclaw loop-video', name: 'Fluxcloud Openclaw Loop (Video)', path: '/backgrounds/fluxcloud openclaw loop.mp4', thumbnail: '/backgrounds/fluxcloud openclaw.png', type: 'video' },
  { id: 'flux-four-image', name: 'Four', path: '/backgrounds/four.png', thumbnail: '/backgrounds/thumbnails/four.jpg' },
  { id: 'flux-nine-image', name: 'Nine', path: '/backgrounds/nine.png', thumbnail: '/backgrounds/thumbnails/nine.jpg' },
  { id: 'flux-one-image', name: 'One', path: '/backgrounds/one.png', thumbnail: '/backgrounds/thumbnails/one.jpg' },
  { id: 'flux-seven-image', name: 'Seven', path: '/backgrounds/seven.png', thumbnail: '/backgrounds/thumbnails/seven.jpg' },
  { id: 'flux-six-image', name: 'Six', path: '/backgrounds/six.png', thumbnail: '/backgrounds/thumbnails/six.jpg' },
  { id: 'flux-ten-image', name: 'Ten', path: '/backgrounds/ten.png', thumbnail: '/backgrounds/thumbnails/ten.jpg' },
  { id: 'flux-three-image', name: 'Three', path: '/backgrounds/three.png', thumbnail: '/backgrounds/thumbnails/three.jpg' },
  { id: 'flux-two-image', name: 'Two', path: '/backgrounds/two.png', thumbnail: '/backgrounds/thumbnails/two.jpg' }
]

export const DISCOVERED_SSP_BACKGROUNDS: BackgroundOption[] = [
  { id: 'ssp-biometric security-video', name: 'Biometric Security (Video)', path: '/products/ssp/backgrounds/biometric security.mp4', thumbnail: '/products/ssp/backgrounds/biometric security.mp4', type: 'video' },
  { id: 'ssp-biometrics security-image', name: 'Biometrics Security', path: '/products/ssp/backgrounds/biometrics security.png', thumbnail: '/products/ssp/backgrounds/thumbnails/biometrics security.jpg' },
  { id: 'ssp-complete audit trail-image', name: 'Complete Audit Trail', path: '/products/ssp/backgrounds/complete audit trail.png', thumbnail: '/products/ssp/backgrounds/thumbnails/complete audit trail.jpg' },
  { id: 'ssp-complete audit trail-video', name: 'Complete Audit Trail (Video)', path: '/products/ssp/backgrounds/complete audit trail.mp4', thumbnail: '/products/ssp/backgrounds/thumbnails/complete audit trail.jpg', type: 'video' },
  { id: 'ssp-fully open source-image', name: 'Fully Open Source', path: '/products/ssp/backgrounds/fully open source.png', thumbnail: '/products/ssp/backgrounds/thumbnails/fully open source.jpg' },
  { id: 'ssp-fully open source-video', name: 'Fully Open Source (Video)', path: '/products/ssp/backgrounds/fully open source.mp4', thumbnail: '/products/ssp/backgrounds/thumbnails/fully open source.jpg', type: 'video' },
  { id: 'ssp-generic - main-image', name: 'Generic Main', path: '/products/ssp/backgrounds/generic - main.png', thumbnail: '/products/ssp/backgrounds/thumbnails/generic - main.jpg' },
  { id: 'ssp-generic - main-video', name: 'Generic Main (Video)', path: '/products/ssp/backgrounds/generic - main.mp4', thumbnail: '/products/ssp/backgrounds/thumbnails/generic - main.jpg', type: 'video' },
  { id: 'ssp-multi chain native-image', name: 'Multi Chain Native', path: '/products/ssp/backgrounds/multi chain native.png', thumbnail: '/products/ssp/backgrounds/thumbnails/multi chain native.jpg' },
  { id: 'ssp-multi chain native-video', name: 'Multi Chain Native (Video)', path: '/products/ssp/backgrounds/multi chain native.mp4', thumbnail: '/products/ssp/backgrounds/thumbnails/multi chain native.jpg', type: 'video' },
  { id: 'ssp-multi party approval-image', name: 'Multi Party Approval', path: '/products/ssp/backgrounds/multi party approval.png', thumbnail: '/products/ssp/backgrounds/thumbnails/multi party approval.jpg' },
  { id: 'ssp-mutli part approval-video', name: 'Mutli Part Approval (Video)', path: '/products/ssp/backgrounds/mutli part approval.mp4', thumbnail: '/products/ssp/backgrounds/mutli part approval.mp4', type: 'video' },
  { id: 'ssp-sec audit halbron-video', name: 'Sec Audit Halbron (Video)', path: '/products/ssp/backgrounds/sec audit halbron.mp4', thumbnail: '/products/ssp/backgrounds/sec audit halbron.mp4', type: 'video' },
  { id: 'ssp-security audited halborn-image', name: 'Security Audited Halborn', path: '/products/ssp/backgrounds/security audited halborn.png', thumbnail: '/products/ssp/backgrounds/thumbnails/security audited halborn.jpg' },
  { id: 'ssp-true self custody-image', name: 'True Self Custody', path: '/products/ssp/backgrounds/true self custody.png', thumbnail: '/products/ssp/backgrounds/thumbnails/true self custody.jpg' },
  { id: 'ssp-true self custody-video', name: 'True Self Custody (Video)', path: '/products/ssp/backgrounds/true self custody.mp4', thumbnail: '/products/ssp/backgrounds/thumbnails/true self custody.jpg', type: 'video' }
]
